### ISSUE TITLE
Create the use case diagram for our project.

### ISSUE THREAD

**Issue by arincdemir** [bounswe/bounswe2024group5#104] opened 2024-03-31 12:29 UTC
## Description
We need the use case diagrams for our project before going further.
We will use this link to access the collaborative webpage for our diagram:
[draw.io link](https://drive.google.com/file/d/1QbJJS1J5EcyW7SQ38RSkC_Gb2j18wuqk/view?usp=sharing)

## Estimated Time
80 mins

## Deadline
Date(31/03/2024) - 23:59

## Reviewer
@ebrarkiziloglu  - Deadline of the review(02/04/2024 - 23:50)

**Comment by set120120** [comment] 2024-03-31 21:48
I've added search part. Could you please continue to add new parts? @ramazanoacar @arincdemir . Also, I've tried to write feed page but I could not do something. Could you please help to do this part?

**Comment by ramazanoacar** [comment] 2024-04-02 07:24
@set120120 yes of course. I think @arincdemir  did some of the parts too. I tried to add the remainings but LucidChart said we are out of free shapes. So, I will transfer this one the add the remainings to draw.io

**Comment by ramazanoacar** [comment] 2024-04-02 08:22
https://drive.google.com/file/d/1QbJJS1J5EcyW7SQ38RSkC_Gb2j18wuqk/view?usp=sharing

it is now empty but i will do my work on this link

**Comment by ramazanoacar** [comment] 2024-04-07 10:44
@set120120 @arincdemir I added the part for Feed Page and transferred everything to above link. However, I am not sure if the issue is completed or not. Do we need to add another parts such as Following and Personal Page or is this enough? If not, what should we add and how we should arrange them? Do you have any ideas? Also, @ebrarkiziloglu what do you think as a reviewer?

**Comment by ebrarkiziloglu** [comment] 2024-04-08 18:20
Thanks everyone. The diagram looks very elaborate! I have a few notes and some design questions for you:

- Inside the `Feed` system boundary, the three use cases under the use case `Interact with Post` were separately connected to the `Backend` actor. So, I took the liberty of connecting `Interact with Post` directly with `Backend` actor instead. 
- I believe `delete history` should extend `see search history` instead of the current include relation, since deleting the history is an optional functionality, wdyt?
- I see that the use cases `publish a post` and `Interact with Post` are in relation with the `backend` actor. With similar logic, should `Search` use cases be connected to `Backend` as well?
- Inside the `search` system boundary, all the `filter by` use cases are currently connected to their corresponding parent use cases by the `include` relations. I think these should be `extends` instead, since filter by functionalities are optional. Could you please provide your reasoning behind this design choice? I might have missed a key point here.

**Comment by ramazanoacar** [comment] 2024-04-11 06:48
@ebrarkiziloglu thanks for your review and comments. However, since we did this separately and individually with other assignees, I believe it would be better for us to make a small meeting and go over your points and make the necessary addition/deletions. What do you think @arincdemir @set120120 do you have time during the holiday?

**Comment by ebrarkiziloglu** [comment] 2024-04-16 09:34
> Hi Ebrar, I revised the search section according to the feedback you gave. Sorry for editing it a little late. Can you check again?

Hi Süleyman, I see that you converted the include relations to extend ones, thank you. 
Yet, I believe the arrows should point to the other directions. 

Also, what do you think about my proposal on creating a sub-use case for`search profile` in my [comment](https://github.com/bounswe/bounswe2024group5/issues/104#issuecomment-2043414062) above?

**Comment by ramazanoacar** [comment] 2024-04-16 10:01
@ebrarkiziloglu since i couldn't attend the meeting this evening. I will duplicate the draw.io file and add your proposals. So that If you decide to add during the meeting you can use duplicate and new one

**Comment by ramazanoacar** [comment] 2024-04-16 10:03
You can use this links:

https://drive.google.com/file/d/1_Kl-MWNIcNKWRYGK8NUCJpuQAAdUNJvm/view?usp=sharing

https://app.diagrams.net/#G1_Kl-MWNIcNKWRYGK8NUCJpuQAAdUNJvm#%7B%22pageId%22%3A%225Y3wF6CpWj2z_y-06vuE%22%7D

**Comment by arincdemir** [comment] 2024-04-16 12:35
I modified the file Ramazan shared above. [this one](https://drive.google.com/file/d/1_Kl-MWNIcNKWRYGK8NUCJpuQAAdUNJvm/view?usp=sharing)
- I fixed the directions of the extend arrows.
- I moved the actors out of the system since that's how use case diagrams work I believe.
- I fixed the normal arrows in the "Feed" part. I changed them to include or extend as needed

**Comment by ramazanoacar** [comment] 2024-04-16 15:34
I added the parts from @ebrarkiziloglu 's comment and changed some of the arrows. However, I mistakenly changed the orders of the system and couldn't revert it because I couldn't find when I did it. So, a check for the arrows and system would be useful in the meeting tonight.

**Comment by ebrarkiziloglu** [comment] 2024-04-16 18:36
We held a meeting with @set120120 to apply the latest changes. We also moved all of your changes from the second file to the original [one](https://drive.google.com/file/d/1QbJJS1J5EcyW7SQ38RSkC_Gb2j18wuqk/view?usp=sharing). 
Could you please have a look at it one last time? @ramazanoacar @arincdemir

**Comment by ramazanoacar** [comment] 2024-04-18 06:33
@ebrarkiziloglu I looked at the changes. They seem nice and okey to me. Thanks for your effort! If @arincdemir is also okey with the changes, we can change the status label to needs review.

**Comment by arincdemir** [comment] 2024-04-20 16:04
@ebrarkiziloglu Looks nice!

**Comment by ramazanoacar** [comment] 2024-04-22 13:46
@ebrarkiziloglu I saw Arınç's comment now, can you review the issue?

**Comment by ebrarkiziloglu** [comment] 2024-04-22 15:59
Hi everyone. Please adjust the feedback from TA (on discord) to the diagram.

**Comment by set120120** [comment] 2024-04-27 17:25
I had a meeting with @ramazanoacar to apply the changes according to feedback. Can you please have a look? @ebrarkiziloglu @arincdemir

**Comment by ebrarkiziloglu** [comment] 2024-04-27 22:46
I reviewed the changes you made according to the TA's feedback. 
I just have one question, should <Issue Log In Error> be considered as a use case? Is it something the user can act on?  
Otherwise, the diagram looks great to me, good work!

**Comment by set120120** [comment] 2024-04-28 12:42
We thought that if the user enters the wrong information while logging in, we should forward him to a new page and ask him to log in again. That's why we didn't remove it.

**Comment by ebrarkiziloglu** [comment] 2024-04-28 12:59
Okay that makes sense to me. Overall, the diagram is ready imo. Would you like to add it to wiki?

**Comment by set120120** [comment] 2024-04-28 13:59
I've added necessary pages and links to wiki. You can close the issue now. Everything is done!

**Comment by ebrarkiziloglu** [comment] 2024-04-30 07:50
Perfect. Great work everyone!

**Closed by ebrarkiziloglu** 2024-04-30 07:50 UTC
Labels: priority: moderate, effort: high, status: need review, type: planning
